# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  macos:
    xcode: "10.1.0"
  working_directory: ~/repo

linux: &linux
  docker:
    - image: circleci/node:10.11
  working_directory: ~/repo

version: 2
jobs:
  setup:
    <<: *linux
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    <<: *linux
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run Build
          command: yarn build
      - save_cache:
          name: Save build
          paths:
            - dist
          key: v1-build-{{ .Branch }}-{{ .Revision }}

  package:
    <<: *linux
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore build
          keys:
            - v1-build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Run Package
          command: yarn package

workflows:
  version: 2
  test_and_release:
    jobs:
      - setup
      - build:
          requires:
            - setup


